export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";
export const REMOVE_VIDEO_SUCCESS = "REMOVE_VIDEO_SUCCESS";

export const SET_NEXT_VIDEO = "SET_NEXT_VIDEO";
